network
xuperchain/xupercore pull request #17
Opened 2020-11-06 07:37 UTC by ownluke

Implementation network interface: p2pv1 & p2pv2

2020-11-06 11:26 UTC, chunhui01 commented on kernel/network/context/context.go
> +type OperateCtxImpl struct {
There is no special requirement to use xcontext.BaseCtx directly.

2020-11-06 11:41 UTC, chunhui01 commented on kernel/network/config/config.go
> +    DefaultNetKeyPath       = "./data/netkeys" 	// node private key path
Absolute path is recommended for file path,It can be obtained through envconf.

2020-11-06 11:52 UTC, chunhui01 approved these changes
LGTM

2020-11-09 13:10 UTC, preminem requested changes

2020-11-09 13:10 UTC, preminem commented on bcs/network/p2pv1/client.go
> +    "errors"
When importing multiple packages, the packages should be grouped. There is no need for a blank line between packages in the same group, and a blank line between packages in different groups. 
Standard library packages should be placed in the first group, third-party library should be placed in the second group, and local library should be placed in the third group.

2020-11-10 08:06 UTC, preminem commented on kernel/network/network.go
> +func CreateNetwork(ctx nctx.DomainCtx, servName string) (Network, error) {
servName may be redundant, that included in the p2p conf of the network context

2020-11-16 09:52 UTC, merged